package map;

public class ManuelRoom {
	private Tile[][] StartMap;

	public ManuelRoom() {
		StartMap = new Tile[][] {
				{ Tile.TREE, Tile.TREE, Tile.TREE, Tile.TREE, Tile.TREE, Tile.TREE,
						Tile.TREE, Tile.TREE, Tile.TREE, Tile.TREE, Tile.TREE,
						Tile.TREE, Tile.TREE, Tile.TREE, Tile.TREE, Tile.TREE,
						Tile.TREE, Tile.TREE, Tile.TREE, Tile.TREE, Tile.TREE,
						Tile.TREE, Tile.TREE, Tile.TREE, Tile.TREE, Tile.TREE,
						Tile.TREE, Tile.TREE, Tile.TREE, Tile.TREE, Tile.TREE,
						Tile.TREE, Tile.TREE, Tile.TREE, Tile.TREE, Tile.TREE,
						Tile.TREE, Tile.TREE, Tile.TREE, Tile.TREE, Tile.TREE },
				{ Tile.TREE, Tile.TREE, Tile.TREE, Tile.TREE, Tile.TREE, Tile.TREE,
						Tile.TREE, Tile.TREE, Tile.TREE, Tile.TREE, Tile.TREE,
						Tile.TREE, Tile.TREE, Tile.TREE, Tile.TREE, Tile.TREE,
						Tile.TREE, Tile.TREE, Tile.TREE, Tile.TREE, Tile.TREE,
						Tile.TREE, Tile.TREE, Tile.TREE, Tile.TREE, Tile.TREE,
						Tile.TREE, Tile.TREE, Tile.TREE, Tile.TREE, Tile.TREE,
						Tile.TREE, Tile.TREE, Tile.TREE, Tile.TREE, Tile.TREE,
						Tile.TREE, Tile.TREE, Tile.TREE, Tile.TREE, Tile.TREE },
				{ Tile.TREE, Tile.TREE, Tile.TREE, Tile.TREE, Tile.TREE, Tile.TREE,
						Tile.TREE, Tile.TREE, Tile.TREE, Tile.TREE, Tile.TREE,
						Tile.TREE, Tile.TREE, Tile.TREE, Tile.TREE, Tile.TREE,
						Tile.TREE, Tile.TREE, Tile.TREE, Tile.TREE, Tile.TREE,
						Tile.TREE, Tile.TREE, Tile.TREE, Tile.TREE, Tile.TREE,
						Tile.TREE, Tile.TREE, Tile.TREE, Tile.TREE, Tile.TREE,
						Tile.TREE, Tile.TREE, Tile.TREE, Tile.TREE, Tile.TREE,
						Tile.TREE, Tile.TREE, Tile.TREE, Tile.TREE, Tile.TREE },
				{ Tile.TREE, Tile.TREE, Tile.TREE, Tile.TREE, Tile.TREE, Tile.TREE,
						Tile.TREE, Tile.TREE, Tile.TREE, Tile.TREE, Tile.TREE,
						Tile.TREE, Tile.TREE, Tile.TREE, Tile.TREE, Tile.TREE,
						Tile.TREE, Tile.TREE, Tile.TREE, Tile.TREE, Tile.TREE,
						Tile.TREE, Tile.TREE, Tile.TREE, Tile.TREE, Tile.TREE,
						Tile.TREE, Tile.TREE, Tile.TREE, Tile.TREE, Tile.TREE,
						Tile.TREE, Tile.TREE, Tile.TREE, Tile.TREE, Tile.TREE,
						Tile.TREE, Tile.TREE, Tile.TREE, Tile.TREE, Tile.TREE },
				{ Tile.TREE, Tile.TREE, Tile.TREE, Tile.TREE, Tile.TREE, Tile.TREE,
						Tile.TREE, Tile.TREE, Tile.TREE, Tile.TREE, Tile.TREE,
						Tile.TREE, Tile.TREE, Tile.TREE, Tile.TREE, Tile.TREE,
						Tile.TREE, Tile.TREE, Tile.TREE, Tile.TREE, Tile.TREE,
						Tile.TREE, Tile.TREE, Tile.TREE, Tile.TREE, Tile.TREE,
						Tile.TREE, Tile.TREE, Tile.TREE, Tile.TREE, Tile.TREE,
						Tile.TREE, Tile.TREE, Tile.TREE, Tile.TREE, Tile.TREE,
						Tile.TREE, Tile.TREE, Tile.TREE, Tile.TREE, Tile.TREE },
				{ Tile.TREE, Tile.TREE, Tile.TREE, Tile.TREE, Tile.TREE, Tile.TREE,
						Tile.TREE, Tile.TREE, Tile.TREE, Tile.TREE, Tile.TREE,
						Tile.TREE, Tile.TREE, Tile.TREE, Tile.TREE, Tile.TREE,
						Tile.TREE, Tile.TREE, Tile.TREE, Tile.TREE, Tile.TREE,
						Tile.TREE, Tile.TREE, Tile.TREE, Tile.TREE, Tile.TREE,
						Tile.TREE, Tile.TREE, Tile.TREE, Tile.TREE, Tile.TREE,
						Tile.TREE, Tile.TREE, Tile.TREE, Tile.TREE, Tile.TREE,
						Tile.TREE, Tile.TREE, Tile.TREE, Tile.TREE, Tile.TREE },
				{ Tile.TREE, Tile.TREE, Tile.TREE, Tile.TREE, Tile.TREE, Tile.TREE,
						Tile.TREE, Tile.TREE, Tile.TREE, Tile.TREE, Tile.TREE,
						Tile.TREE, Tile.TREE, Tile.TREE, Tile.TREE, Tile.TREE,
						Tile.TREE, Tile.TREE, Tile.TREE, Tile.TREE, Tile.TREE,
						Tile.TREE, Tile.TREE, Tile.TREE, Tile.TREE, Tile.TREE,
						Tile.TREE, Tile.TREE, Tile.TREE, Tile.TREE, Tile.TREE,
						Tile.TREE, Tile.TREE, Tile.TREE, Tile.TREE, Tile.TREE,
						Tile.TREE, Tile.TREE, Tile.TREE, Tile.TREE, Tile.TREE },
				{ Tile.DIRT, Tile.DIRT, Tile.DIRT, Tile.DIRT, Tile.DIRT, Tile.DIRT,
						Tile.FENCE, Tile.DIRT, Tile.DIRT, Tile.DIRT, Tile.DIRT,
						Tile.DIRT, Tile.DIRT, Tile.DIRT, Tile.DIRT, Tile.DIRT,
						Tile.DIRT, Tile.DIRT, Tile.DIRT, Tile.DIRT, Tile.DIRT,
						Tile.DIRT, Tile.DIRT, Tile.DIRT, Tile.DIRT, Tile.DIRT,
						Tile.DIRT, Tile.DIRT, Tile.DIRT, Tile.TREE, Tile.TREE,
						Tile.TREE, Tile.TREE, Tile.TREE, Tile.TREE, Tile.TREE,
						Tile.TREE, Tile.TREE, Tile.TREE, Tile.TREE, Tile.TREE },
				{ Tile.DIRT, Tile.DIRT, Tile.DIRT, Tile.DIRT, Tile.DIRT, Tile.DIRT,
						Tile.ENTERENCE, Tile.DIRT, Tile.DIRT, Tile.DIRT,
						Tile.DIRT, Tile.DIRT, Tile.DIRT, Tile.DIRT, Tile.DIRT,
						Tile.DIRT, Tile.DIRT, Tile.DIRT, Tile.DIRT, Tile.DIRT,
						Tile.DIRT, Tile.DIRT, Tile.DIRT, Tile.DIRT, Tile.DIRT,
						Tile.DIRT, Tile.DIRT, Tile.DIRT, Tile.DIRT, Tile.TREE,
						Tile.TREE, Tile.TREE, Tile.TREE, Tile.TREE, Tile.TREE,
						Tile.TREE, Tile.TREE, Tile.TREE, Tile.TREE, Tile.TREE,
						Tile.TREE },
				{ Tile.TREE, Tile.DIRT, Tile.DIRT, Tile.DIRT, Tile.DIRT, Tile.DIRT,
						Tile.FENCE, Tile.DIRT, Tile.DIRT, Tile.DIRT, Tile.DIRT,
						Tile.DIRT, Tile.DIRT, Tile.DIRT, Tile.DIRT, Tile.DIRT,
						Tile.DIRT, Tile.DIRT, Tile.DIRT, Tile.DIRT, Tile.DIRT,
						Tile.DIRT, Tile.DIRT, Tile.DIRT, Tile.DIRT, Tile.DIRT,
						Tile.DIRT, Tile.DIRT, Tile.DIRT, Tile.TREE, Tile.TREE,
						Tile.TREE, Tile.TREE, Tile.TREE, Tile.TREE, Tile.TREE,
						Tile.TREE, Tile.TREE, Tile.TREE, Tile.TREE, Tile.TREE },
				{ Tile.TREE, Tile.TREE, Tile.TREE, Tile.TREE, Tile.TREE, Tile.TREE,
						Tile.TREE, Tile.DIRT, Tile.DIRT, Tile.DIRT, Tile.DIRT,
						Tile.DIRT, Tile.DIRT, Tile.DIRT, Tile.DIRT, Tile.DIRT,
						Tile.DIRT, Tile.DIRT, Tile.DIRT, Tile.DIRT, Tile.DIRT,
						Tile.DIRT, Tile.DIRT, Tile.DIRT, Tile.DIRT, Tile.DIRT,
						Tile.DIRT, Tile.DIRT, Tile.DIRT, Tile.TREE, Tile.TREE,
						Tile.TREE, Tile.TREE, Tile.TREE, Tile.TREE, Tile.TREE,
						Tile.TREE, Tile.TREE, Tile.TREE, Tile.TREE, Tile.TREE },
				{ Tile.TREE, Tile.TREE, Tile.TREE, Tile.TREE, Tile.TREE, Tile.TREE,
						Tile.TREE, Tile.DIRT, Tile.DIRT, Tile.DIRT, Tile.DIRT,
						Tile.DIRT, Tile.DIRT, Tile.DIRT, Tile.DIRT, Tile.DIRT,
						Tile.DIRT, Tile.DIRT, Tile.DIRT, Tile.DIRT, Tile.DIRT,
						Tile.DIRT, Tile.DIRT, Tile.DIRT, Tile.DIRT, Tile.DIRT,
						Tile.DIRT, Tile.DIRT, Tile.DIRT, Tile.TREE, Tile.TREE,
						Tile.TREE, Tile.TREE, Tile.TREE, Tile.TREE, Tile.TREE,
						Tile.TREE, Tile.TREE, Tile.TREE, Tile.TREE, Tile.TREE },
				{ Tile.TREE, Tile.TREE, Tile.TREE, Tile.TREE, Tile.TREE, Tile.TREE,
						Tile.TREE, Tile.DIRT, Tile.DIRT, Tile.DIRT, Tile.DIRT,
						Tile.DIRT, Tile.DIRT, Tile.DIRT, Tile.DIRT, Tile.DIRT,
						Tile.DIRT, Tile.DIRT, Tile.DIRT, Tile.DIRT, Tile.DIRT,
						Tile.DIRT, Tile.DIRT, Tile.DIRT, Tile.DIRT, Tile.DIRT,
						Tile.DIRT, Tile.DIRT, Tile.DIRT, Tile.TREE, Tile.TREE,
						Tile.TREE, Tile.TREE, Tile.TREE, Tile.TREE, Tile.TREE,
						Tile.TREE, Tile.TREE, Tile.TREE, Tile.TREE, Tile.TREE },
				{ Tile.TREE, Tile.TREE, Tile.TREE, Tile.TREE, Tile.TREE, Tile.TREE,
						Tile.TREE, Tile.DIRT, Tile.DIRT, Tile.DIRT, Tile.DIRT,
						Tile.DIRT, Tile.DIRT, Tile.DIRT, Tile.DIRT, Tile.DIRT,
						Tile.DIRT, Tile.DIRT, Tile.DIRT, Tile.DIRT, Tile.DIRT,
						Tile.DIRT, Tile.DIRT, Tile.DIRT, Tile.DIRT, Tile.DIRT,
						Tile.DIRT, Tile.DIRT, Tile.DIRT, Tile.TREE, Tile.TREE,
						Tile.TREE, Tile.TREE, Tile.TREE, Tile.TREE, Tile.TREE,
						Tile.TREE, Tile.TREE, Tile.TREE, Tile.TREE, Tile.TREE },
				{ Tile.TREE, Tile.TREE, Tile.TREE, Tile.TREE, Tile.TREE, Tile.TREE,
						Tile.TREE, Tile.DIRT, Tile.DIRT, Tile.DIRT, Tile.DIRT,
						Tile.DIRT, Tile.DIRT, Tile.DIRT, Tile.DIRT, Tile.DIRT,
						Tile.DIRT, Tile.DIRT, Tile.DIRT, Tile.DIRT, Tile.DIRT,
						Tile.DIRT, Tile.DIRT, Tile.DIRT, Tile.DIRT, Tile.DIRT,
						Tile.DIRT, Tile.DIRT, Tile.DIRT, Tile.TREE, Tile.TREE,
						Tile.TREE, Tile.TREE, Tile.TREE, Tile.TREE, Tile.TREE,
						Tile.TREE, Tile.TREE, Tile.TREE, Tile.TREE, Tile.TREE },
				{ Tile.TREE, Tile.TREE, Tile.TREE, Tile.TREE, Tile.TREE, Tile.TREE,
						Tile.TREE, Tile.DIRT, Tile.DIRT, Tile.DIRT, Tile.DIRT,
						Tile.DIRT, Tile.DIRT, Tile.DIRT, Tile.DIRT, Tile.DIRT,
						Tile.DIRT, Tile.DIRT, Tile.DIRT, Tile.DIRT, Tile.DIRT,
						Tile.DIRT, Tile.DIRT, Tile.DIRT, Tile.DIRT, Tile.DIRT,
						Tile.DIRT, Tile.DIRT, Tile.DIRT, Tile.TREE, Tile.TREE,
						Tile.TREE, Tile.TREE, Tile.TREE, Tile.TREE, Tile.TREE,
						Tile.TREE, Tile.TREE, Tile.TREE, Tile.TREE, Tile.TREE },
				{ Tile.TREE, Tile.TREE, Tile.TREE, Tile.TREE, Tile.TREE, Tile.TREE,
						Tile.TREE, Tile.DIRT, Tile.DIRT, Tile.DIRT, Tile.DIRT,
						Tile.DIRT, Tile.DIRT, Tile.DIRT, Tile.DIRT, Tile.DIRT,
						Tile.DIRT, Tile.DIRT, Tile.DIRT, Tile.DIRT, Tile.DIRT,
						Tile.DIRT, Tile.DIRT, Tile.DIRT, Tile.DIRT, Tile.DIRT,
						Tile.DIRT, Tile.DIRT, Tile.DIRT, Tile.DIRT, Tile.DIRT,
						Tile.DIRT, Tile.DIRT, Tile.DIRT, Tile.DIRT, Tile.TREE,
						Tile.TREE, Tile.TREE, Tile.TREE, Tile.TREE, Tile.TREE },
				{ Tile.TREE, Tile.TREE, Tile.TREE, Tile.TREE, Tile.TREE, Tile.TREE,
						Tile.TREE, Tile.DIRT, Tile.DIRT, Tile.DIRT, Tile.DIRT,
						Tile.DIRT, Tile.DIRT, Tile.DIRT, Tile.DIRT, Tile.DIRT,
						Tile.DIRT, Tile.DIRT, Tile.DIRT, Tile.DIRT, Tile.DIRT,
						Tile.DIRT, Tile.DIRT, Tile.DIRT, Tile.DIRT, Tile.DIRT,
						Tile.DIRT, Tile.DIRT, Tile.DIRT, Tile.TREE, Tile.TREE,
						Tile.TREE, Tile.TREE, Tile.TREE, Tile.DIRT, Tile.TREE,
						Tile.TREE, Tile.TREE, Tile.TREE, Tile.TREE, Tile.TREE },
				{ Tile.TREE, Tile.TREE, Tile.TREE, Tile.TREE, Tile.TREE, Tile.TREE,
						Tile.TREE, Tile.DIRT, Tile.DIRT, Tile.DIRT, Tile.DIRT,
						Tile.DIRT, Tile.DIRT, Tile.DIRT, Tile.DIRT, Tile.DIRT,
						Tile.DIRT, Tile.DIRT, Tile.DIRT, Tile.DIRT, Tile.DIRT,
						Tile.DIRT, Tile.DIRT, Tile.DIRT, Tile.DIRT, Tile.DIRT,
						Tile.DIRT, Tile.DIRT, Tile.DIRT, Tile.TREE, Tile.TREE,
						Tile.TREE, Tile.TREE, Tile.TREE, Tile.DIRT, Tile.TREE,
						Tile.TREE, Tile.TREE, Tile.TREE, Tile.TREE, Tile.TREE },
				{ Tile.TREE, Tile.TREE, Tile.TREE, Tile.TREE, Tile.TREE, Tile.TREE,
						Tile.TREE, Tile.DIRT, Tile.DIRT, Tile.DIRT, Tile.DIRT,
						Tile.DIRT, Tile.DIRT, Tile.DIRT, Tile.DIRT, Tile.DIRT,
						Tile.DIRT, Tile.DIRT, Tile.DIRT, Tile.DIRT, Tile.DIRT,
						Tile.DIRT, Tile.DIRT, Tile.DIRT, Tile.DIRT, Tile.DIRT,
						Tile.DIRT, Tile.DIRT, Tile.DIRT, Tile.TREE, Tile.TREE,
						Tile.TREE, Tile.TREE, Tile.TREE, Tile.DIRT, Tile.TREE,
						Tile.TREE, Tile.TREE, Tile.TREE, Tile.TREE, Tile.TREE },
				{ Tile.TREE, Tile.TREE, Tile.TREE, Tile.TREE, Tile.TREE, Tile.TREE,
						Tile.TREE, Tile.DIRT, Tile.DIRT, Tile.DIRT, Tile.DIRT,
						Tile.DIRT, Tile.DIRT, Tile.DIRT, Tile.DIRT, Tile.DIRT,
						Tile.DIRT, Tile.DIRT, Tile.DIRT, Tile.DIRT, Tile.DIRT,
						Tile.DIRT, Tile.DIRT, Tile.DIRT, Tile.DIRT, Tile.DIRT,
						Tile.DIRT, Tile.DIRT, Tile.DIRT, Tile.TREE, Tile.TREE,
						Tile.TREE, Tile.TREE, Tile.TREE, Tile.DIRT, Tile.TREE,
						Tile.TREE, Tile.TREE, Tile.TREE, Tile.TREE, Tile.TREE },
				{ Tile.TREE, Tile.TREE, Tile.TREE, Tile.TREE, Tile.TREE, Tile.TREE,
						Tile.TREE, Tile.DIRT, Tile.DIRT, Tile.DIRT, Tile.DIRT,
						Tile.DIRT, Tile.DIRT, Tile.DIRT, Tile.DIRT, Tile.DIRT,
						Tile.DIRT, Tile.DIRT, Tile.DIRT, Tile.DIRT, Tile.DIRT,
						Tile.DIRT, Tile.DIRT, Tile.DIRT, Tile.DIRT, Tile.DIRT,
						Tile.DIRT, Tile.DIRT, Tile.DIRT, Tile.TREE, Tile.TREE,
						Tile.TREE, Tile.TREE, Tile.TREE, Tile.DIRT, Tile.TREE,
						Tile.TREE, Tile.TREE, Tile.TREE, Tile.TREE, Tile.TREE },
				{ Tile.TREE, Tile.TREE, Tile.TREE, Tile.TREE, Tile.TREE, Tile.TREE,
						Tile.TREE, Tile.DIRT, Tile.DIRT, Tile.DIRT, Tile.DIRT,
						Tile.DIRT, Tile.DIRT, Tile.DIRT, Tile.DIRT, Tile.DIRT,
						Tile.DIRT, Tile.DIRT, Tile.DIRT, Tile.DIRT, Tile.DIRT,
						Tile.DIRT, Tile.DIRT, Tile.DIRT, Tile.DIRT, Tile.DIRT,
						Tile.DIRT, Tile.DIRT, Tile.DIRT, Tile.TREE, Tile.TREE,
						Tile.TREE, Tile.TREE, Tile.TREE, Tile.DIRT, Tile.TREE,
						Tile.TREE, Tile.TREE, Tile.TREE, Tile.TREE, Tile.TREE },
				{ Tile.TREE, Tile.TREE, Tile.TREE, Tile.TREE, Tile.TREE, Tile.TREE,
						Tile.TREE, Tile.TREE, Tile.TREE, Tile.TREE, Tile.TREE,
						Tile.TREE, Tile.TREE, Tile.TREE, Tile.TREE, Tile.TREE,
						Tile.DIRT, Tile.DIRT, Tile.DIRT, Tile.DIRT, Tile.TREE,
						Tile.TREE, Tile.TREE, Tile.TREE, Tile.TREE, Tile.TREE,
						Tile.TREE, Tile.TREE, Tile.TREE, Tile.TREE, Tile.TREE,
						Tile.TREE, Tile.TREE, Tile.TREE, Tile.DIRT, Tile.TREE,
						Tile.TREE, Tile.TREE, Tile.TREE, Tile.TREE, Tile.TREE },
				{ Tile.TREE, Tile.TREE, Tile.TREE, Tile.TREE, Tile.TREE, Tile.TREE,
						Tile.TREE, Tile.TREE, Tile.TREE, Tile.TREE, Tile.TREE,
						Tile.TREE, Tile.TREE, Tile.TREE, Tile.TREE, Tile.TREE,
						Tile.DIRT, Tile.DIRT, Tile.DIRT, Tile.DIRT, Tile.TREE,
						Tile.TREE, Tile.TREE, Tile.TREE, Tile.TREE, Tile.TREE,
						Tile.TREE, Tile.TREE, Tile.TREE, Tile.TREE, Tile.TREE,
						Tile.TREE, Tile.TREE, Tile.TREE, Tile.DIRT, Tile.TREE,
						Tile.TREE, Tile.TREE, Tile.TREE, Tile.TREE, Tile.TREE },
				{ Tile.TREE, Tile.TREE, Tile.TREE, Tile.TREE, Tile.TREE, Tile.TREE,
						Tile.TREE, Tile.TREE, Tile.TREE, Tile.TREE, Tile.TREE,
						Tile.TREE, Tile.TREE, Tile.TREE, Tile.TREE, Tile.TREE,
						Tile.DIRT, Tile.DIRT, Tile.DIRT, Tile.DIRT, Tile.TREE,
						Tile.TREE, Tile.TREE, Tile.TREE, Tile.TREE, Tile.TREE,
						Tile.TREE, Tile.TREE, Tile.TREE, Tile.TREE, Tile.TREE,
						Tile.TREE, Tile.TREE, Tile.TREE, Tile.DIRT, Tile.TREE,
						Tile.TREE, Tile.TREE, Tile.TREE, Tile.TREE, Tile.TREE },
				{ Tile.TREE, Tile.TREE, Tile.TREE, Tile.TREE, Tile.TREE, Tile.TREE,
						Tile.DIRT, Tile.DIRT, Tile.DIRT, Tile.DIRT, Tile.DIRT,
						Tile.DIRT, Tile.DIRT, Tile.DIRT, Tile.DIRT, Tile.DIRT,
						Tile.DIRT, Tile.DIRT, Tile.DIRT, Tile.DIRT, Tile.DIRT,
						Tile.DIRT, Tile.DIRT, Tile.DIRT, Tile.DIRT, Tile.DIRT,
						Tile.DIRT, Tile.DIRT, Tile.DIRT, Tile.DIRT, Tile.DIRT,
						Tile.DIRT, Tile.DIRT, Tile.DIRT, Tile.DIRT, Tile.TREE,
						Tile.TREE, Tile.TREE, Tile.TREE, Tile.TREE, Tile.TREE },
				{ Tile.TREE, Tile.TREE, Tile.TREE, Tile.TREE, Tile.TREE, Tile.TREE,
						Tile.DIRT, Tile.DIRT, Tile.DIRT, Tile.DIRT, Tile.DIRT,
						Tile.DIRT, Tile.DIRT, Tile.DIRT, Tile.DIRT, Tile.DIRT,
						Tile.DIRT, Tile.DIRT, Tile.DIRT, Tile.DIRT, Tile.DIRT,
						Tile.DIRT, Tile.DIRT, Tile.DIRT, Tile.DIRT, Tile.DIRT,
						Tile.DIRT, Tile.DIRT, Tile.DIRT, Tile.DIRT, Tile.DIRT,
						Tile.DIRT, Tile.DIRT, Tile.DIRT, Tile.DIRT, Tile.DIRT,
						Tile.DIRT, Tile.TREE, Tile.TREE, Tile.TREE, Tile.TREE },
				{ Tile.TREE, Tile.TREE, Tile.TREE, Tile.TREE, Tile.TREE, Tile.TREE,
						Tile.DIRT, Tile.DIRT, Tile.DIRT, Tile.DIRT, Tile.DIRT,
						Tile.DIRT, Tile.DIRT, Tile.DIRT, Tile.DIRT, Tile.DIRT,
						Tile.DIRT, Tile.DIRT, Tile.DIRT, Tile.DIRT, Tile.DIRT,
						Tile.DIRT, Tile.DIRT, Tile.DIRT, Tile.DIRT, Tile.DIRT,
						Tile.DIRT, Tile.DIRT, Tile.DIRT, Tile.DIRT, Tile.DIRT,
						Tile.DIRT, Tile.DIRT, Tile.DIRT, Tile.DIRT, Tile.DIRT,
						Tile.DIRT, Tile.TREE, Tile.TREE, Tile.TREE, Tile.TREE },
				{ Tile.TREE, Tile.TREE, Tile.TREE, Tile.TREE, Tile.TREE, Tile.TREE,
						Tile.DIRT, Tile.DIRT, Tile.DIRT, Tile.DIRT, Tile.DIRT,
						Tile.DIRT, Tile.DIRT, Tile.DIRT, Tile.DIRT, Tile.DIRT,
						Tile.DIRT, Tile.DIRT, Tile.DIRT, Tile.DIRT, Tile.DIRT,
						Tile.DIRT, Tile.DIRT, Tile.DIRT, Tile.DIRT, Tile.DIRT,
						Tile.DIRT, Tile.DIRT, Tile.DIRT, Tile.DIRT, Tile.DIRT,
						Tile.DIRT, Tile.DIRT, Tile.DIRT, Tile.DIRT, Tile.DIRT,
						Tile.DIRT, Tile.TREE, Tile.TREE, Tile.TREE, Tile.TREE },
				{ Tile.TREE, Tile.TREE, Tile.TREE, Tile.TREE, Tile.TREE, Tile.TREE,
						Tile.TREE, Tile.TREE, Tile.TREE, Tile.TREE, Tile.TREE,
						Tile.TREE, Tile.TREE, Tile.TREE, Tile.TREE, Tile.TREE,
						Tile.TREE, Tile.TREE, Tile.TREE, Tile.TREE, Tile.TREE,
						Tile.TREE, Tile.TREE, Tile.TREE, Tile.TREE, Tile.TREE,
						Tile.TREE, Tile.TREE, Tile.TREE, Tile.DIRT, Tile.DIRT,
						Tile.DIRT, Tile.DIRT, Tile.DIRT, Tile.DIRT, Tile.DIRT,
						Tile.DIRT, Tile.TREE, Tile.TREE, Tile.TREE, Tile.TREE },
				{ Tile.TREE, Tile.TREE, Tile.TREE, Tile.TREE, Tile.TREE, Tile.TREE,
						Tile.TREE, Tile.TREE, Tile.TREE, Tile.TREE, Tile.TREE,
						Tile.TREE, Tile.TREE, Tile.TREE, Tile.TREE, Tile.TREE,
						Tile.TREE, Tile.TREE, Tile.TREE, Tile.TREE, Tile.TREE,
						Tile.TREE, Tile.TREE, Tile.TREE, Tile.TREE, Tile.TREE,
						Tile.TREE, Tile.TREE, Tile.TREE, Tile.DIRT, Tile.DIRT,
						Tile.DIRT, Tile.DIRT, Tile.DIRT, Tile.DIRT, Tile.DIRT,
						Tile.DIRT, Tile.TREE, Tile.TREE, Tile.TREE, Tile.TREE },
				{ Tile.TREE, Tile.TREE, Tile.TREE, Tile.TREE, Tile.TREE, Tile.TREE,
						Tile.TREE, Tile.TREE, Tile.TREE, Tile.TREE, Tile.TREE,
						Tile.TREE, Tile.TREE, Tile.TREE, Tile.TREE, Tile.TREE,
						Tile.TREE, Tile.TREE, Tile.TREE, Tile.TREE, Tile.TREE,
						Tile.TREE, Tile.TREE, Tile.TREE, Tile.TREE, Tile.TREE,
						Tile.TREE, Tile.TREE, Tile.TREE, Tile.TREE, Tile.TREE,
						Tile.TREE, Tile.TREE, Tile.TREE, Tile.TREE, Tile.TREE,
						Tile.TREE, Tile.TREE, Tile.TREE, Tile.TREE, Tile.TREE },
				{ Tile.TREE, Tile.TREE, Tile.TREE, Tile.TREE, Tile.TREE, Tile.TREE,
						Tile.TREE, Tile.TREE, Tile.TREE, Tile.TREE, Tile.TREE,
						Tile.TREE, Tile.TREE, Tile.TREE, Tile.TREE, Tile.TREE,
						Tile.TREE, Tile.TREE, Tile.TREE, Tile.TREE, Tile.TREE,
						Tile.TREE, Tile.TREE, Tile.TREE, Tile.TREE, Tile.TREE,
						Tile.TREE, Tile.TREE, Tile.TREE, Tile.TREE, Tile.TREE,
						Tile.TREE, Tile.TREE, Tile.TREE, Tile.TREE, Tile.TREE,
						Tile.TREE, Tile.TREE, Tile.TREE, Tile.TREE, Tile.TREE },
				{ Tile.TREE, Tile.TREE, Tile.TREE, Tile.TREE, Tile.TREE, Tile.TREE,
						Tile.TREE, Tile.TREE, Tile.TREE, Tile.TREE, Tile.TREE,
						Tile.TREE, Tile.TREE, Tile.TREE, Tile.TREE, Tile.TREE,
						Tile.TREE, Tile.TREE, Tile.TREE, Tile.TREE, Tile.TREE,
						Tile.TREE, Tile.TREE, Tile.TREE, Tile.TREE, Tile.TREE,
						Tile.TREE, Tile.TREE, Tile.TREE, Tile.TREE, Tile.TREE,
						Tile.TREE, Tile.TREE, Tile.TREE, Tile.TREE, Tile.TREE,
						Tile.TREE, Tile.TREE, Tile.TREE, Tile.TREE, Tile.TREE },
				{ Tile.TREE, Tile.TREE, Tile.TREE, Tile.TREE, Tile.TREE, Tile.TREE,
						Tile.TREE, Tile.TREE, Tile.TREE, Tile.TREE, Tile.TREE,
						Tile.TREE, Tile.TREE, Tile.TREE, Tile.TREE, Tile.TREE,
						Tile.TREE, Tile.TREE, Tile.TREE, Tile.TREE, Tile.TREE,
						Tile.TREE, Tile.TREE, Tile.TREE, Tile.TREE, Tile.TREE,
						Tile.TREE, Tile.TREE, Tile.TREE, Tile.TREE, Tile.TREE,
						Tile.TREE, Tile.TREE, Tile.TREE, Tile.TREE, Tile.TREE,
						Tile.TREE, Tile.TREE, Tile.TREE, Tile.TREE, Tile.TREE },
				{ Tile.TREE, Tile.TREE, Tile.TREE, Tile.TREE, Tile.TREE, Tile.TREE,
						Tile.TREE, Tile.TREE, Tile.TREE, Tile.TREE, Tile.TREE,
						Tile.TREE, Tile.TREE, Tile.TREE, Tile.TREE, Tile.TREE,
						Tile.TREE, Tile.TREE, Tile.TREE, Tile.TREE, Tile.TREE,
						Tile.TREE, Tile.TREE, Tile.TREE, Tile.TREE, Tile.TREE,
						Tile.TREE, Tile.TREE, Tile.TREE, Tile.TREE, Tile.TREE,
						Tile.TREE, Tile.TREE, Tile.TREE, Tile.TREE, Tile.TREE,
						Tile.TREE, Tile.TREE, Tile.TREE, Tile.TREE, Tile.TREE },
				{ Tile.TREE, Tile.TREE, Tile.TREE, Tile.TREE, Tile.TREE, Tile.TREE,
						Tile.TREE, Tile.TREE, Tile.TREE, Tile.TREE, Tile.TREE,
						Tile.TREE, Tile.TREE, Tile.TREE, Tile.TREE, Tile.TREE,
						Tile.TREE, Tile.TREE, Tile.TREE, Tile.TREE, Tile.TREE,
						Tile.TREE, Tile.TREE, Tile.TREE, Tile.TREE, Tile.TREE,
						Tile.TREE, Tile.TREE, Tile.TREE, Tile.TREE, Tile.TREE,
						Tile.TREE, Tile.TREE, Tile.TREE, Tile.TREE, Tile.TREE,
						Tile.TREE, Tile.TREE, Tile.TREE, Tile.TREE, Tile.TREE },
				{ Tile.TREE, Tile.TREE, Tile.TREE, Tile.TREE, Tile.TREE, Tile.TREE,
						Tile.TREE, Tile.TREE, Tile.TREE, Tile.TREE, Tile.TREE,
						Tile.TREE, Tile.TREE, Tile.TREE, Tile.TREE, Tile.TREE,
						Tile.TREE, Tile.TREE, Tile.TREE, Tile.TREE, Tile.TREE,
						Tile.TREE, Tile.TREE, Tile.TREE, Tile.TREE, Tile.TREE,
						Tile.TREE, Tile.TREE, Tile.TREE, Tile.TREE, Tile.TREE,
						Tile.TREE, Tile.TREE, Tile.TREE, Tile.TREE, Tile.TREE,
						Tile.TREE, Tile.TREE, Tile.TREE, Tile.TREE, Tile.TREE },
				{ Tile.TREE, Tile.TREE, Tile.TREE, Tile.TREE, Tile.TREE, Tile.TREE,
						Tile.TREE, Tile.TREE, Tile.TREE, Tile.TREE, Tile.TREE,
						Tile.TREE, Tile.TREE, Tile.TREE, Tile.TREE, Tile.TREE,
						Tile.TREE, Tile.TREE, Tile.TREE, Tile.TREE, Tile.TREE,
						Tile.TREE, Tile.TREE, Tile.TREE, Tile.TREE, Tile.TREE,
						Tile.TREE, Tile.TREE, Tile.TREE, Tile.TREE, Tile.TREE,
						Tile.TREE, Tile.TREE, Tile.TREE, Tile.TREE, Tile.TREE,
						Tile.TREE, Tile.TREE, Tile.TREE, Tile.TREE, Tile.TREE } };
	}
	
	public Tile[][] getStartMap(){
		return StartMap;
	}

}
